//
//  SceneOneWorker.swift
//  ExpandableUITableCell
//
//  Created by Ke Ma on 21/07/2017.
//  Copyright (c) 2017 Ke Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SceneOneWorker
{  
  func fetchData() -> [String]
  {
    return ["Collapsible Content One",
            "Collapsible Content Two I have a very long content, so I am much taller than anyone else",
            "Collapsible Content Three",
            "Collapsible Content Four",
            "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            "Collapsible Content Six",
            "Collapsible Content Seven",
            "Collapsible Content Eight",
            "Collapsible Content Nine",
            "Collapsible Content Ten",
    ]
  }
}
