//
//  SceneOneRouter.swift
//  ExpandableUITableCell
//
//  Created by Ke Ma on 21/07/2017.
//  Copyright (c) 2017 Ke Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SceneOneRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SceneOneDataPassing
{
  var dataStore: SceneOneDataStore? { get }
}

class SceneOneRouter: NSObject, SceneOneRoutingLogic, SceneOneDataPassing
{
  weak var viewController: SceneOneViewController?
  var dataStore: SceneOneDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: SceneOneViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: SceneOneDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
