//
//  SceneOnePresenter.swift
//  ExpandableUITableCell
//
//  Created by Ke Ma on 21/07/2017.
//  Copyright (c) 2017 Ke Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SceneOnePresentationLogic
{
  func presentData(response: SceneOne.SceneOne.Response)
}

class SceneOnePresenter: SceneOnePresentationLogic
{
  weak var viewController: SceneOneDisplayLogic?
  
  // MARK: Present Data to OneSceneViewController
  func presentData(response: SceneOne.SceneOne.Response) {
    let viewModel = SceneOne.SceneOne.ViewModel(data: response.data)
    viewController?.receiveData(viewModel: viewModel)
  }
}
