//
//  SceneOneInteractor.swift
//  ExpandableUITableCell
//
//  Created by Ke Ma on 21/07/2017.
//  Copyright (c) 2017 Ke Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SceneOneBusinessLogic
{
  func fetchData()
}

protocol SceneOneDataStore
{
  //var name: String { get set }
}

class SceneOneInteractor: SceneOneBusinessLogic, SceneOneDataStore
{
  var presenter: SceneOnePresentationLogic?
  var worker: SceneOneWorker?
  //var name: String = ""

  // MARK: Fetch Data for table view
  func fetchData()
  {
    worker = SceneOneWorker()
    let data = worker?.fetchData()
    
    let response = SceneOne.SceneOne.Response(data: data!)
    presenter?.presentData(response: response)
  }
}
