//
//  SceneOneModels.swift
//  ExpandableUITableCell
//
//  Created by Ke Ma on 21/07/2017.
//  Copyright (c) 2017 Ke Ma. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum SceneOne
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
    }
    struct ViewModel
    {
    }
  }
  enum SceneOne
  {
    struct Request
    {
    }
    struct Response
    {
      var data : [String]
    }
    struct ViewModel
    {
      var data: [String]
    }
  }
}
